"""Initial migration

Revision ID: 86ed187157f0
Revises: 
Create Date: 2024-10-12 19:25:07.258743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ed187157f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_status',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('file_status_detail',
    sa.Column('status_detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('status_detail', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['file_status.status_id'], ),
    sa.PrimaryKeyConstraint('status_detail_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_status_detail')
    op.drop_table('file_status')
    # ### end Alembic commands ###
